"""empty message

Revision ID: 547a3397ac98
Revises: b0807823407a
Create Date: 2024-10-18 11:48:07.225331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '547a3397ac98'
down_revision: Union[str, None] = 'b0807823407a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('date_time', sa.DateTime(), nullable=False))
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'content',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('messages', 'date_time')
    # ### end Alembic commands ###
