"""empty message

Revision ID: d01320961193
Revises: a894d41847d1
Create Date: 2024-10-20 18:54:29.260663

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d01320961193"
down_revision: Union[str, None] = "a894d41847d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("telegram_id", sa.Integer(), nullable=False))
    op.drop_column("users", "telegraim_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("telegraim_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_column("users", "telegram_id")
    # ### end Alembic commands ###
